#!/bin/bash -l 
#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=2 
#SBATCH --ntasks=2 
#SBATCH --cpus-per-task=6 
#SBATCH --mem=2gb 
#SBATCH --time=00:20:00 
#SBATCH --account=UniKoeln 
#SBATCH --partition=devel
#SBATCH --mail-user=rmilk@uni-koeln.de
#SBATCH --mail-type=end 

source $HOME/.modules
BIN=/scratch/rmilk/dune/dune-multiscale/elliptic_msfem
NODES=1
PROCS=2
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/dune-multiscale/DEBUG_ -grids.macro_cells_per_dim 5 -grids.micro_cells_per_macrocell_dim 5  -threading.max_threads 6"
srun -n $PROCS -N $NODES $BIN ${OPT} 

