#!/bin/bash -l 
#SBATCH --nodes=64
#SBATCH --ntasks-per-node=1 
#SBATCH --ntasks=64
#SBATCH --cpus-per-task=12
#SBATCH --mem=4gb 
#SBATCH --time=02:00:00 
#SBATCH --account=UniKoeln 
#SBATCH --partition=mpi
#SBATCH --constraint=[inca12*64]
#SBATCH --exclusive
#SBATCH -o out_%j_%N
#SBATCH -e out_%j_%N.err
#SBATCH --mail-user=rmilk@uni-koeln.de
#SBATCH --mail-type=end 

source $HOME/.modules
MA=16
MI=16
BIN=/scratch/rmilk/multiscale-build/dune-multiscale/elliptic_msfem
COMMON="-threading.partition_factor 1"
DATADIR=speedup
SUF="_T12"

NODES=128
PROCS=128
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/dune-multiscale/${DATADIR}_12C_n${PROCS}_${MA}x${MI}_${SUF} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI ${COMMON}"
#srun -n $PROCS -N $NODES $BIN ${OPT}

NODES=64
PROCS=64 
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/dune-multiscale/${DATADIR}_12C_n${PROCS}_${MA}x${MI}_${SUF} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI ${COMMON}"
srun -n $PROCS -N $NODES $BIN ${OPT} &

NODES=32
PROCS=32
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/dune-multiscale/${DATADIR}_12C_n${PROCS}_${MA}x${MI}_${SUF} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI ${COMMON}"
srun -n $PROCS -N $NODES $BIN ${OPT} &

NODES=16
PROCS=16
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/dune-multiscale/${DATADIR}_12C_n${PROCS}_${MA}x${MI}_${SUF} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI ${COMMON}"
srun -n $PROCS -N $NODES $BIN ${OPT} &

NODES=8
PROCS=8
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/dune-multiscale/${DATADIR}_12C_n${PROCS}_${MA}x${MI}_${SUF} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI ${COMMON}"
srun -n $PROCS -N $NODES $BIN ${OPT} &

NODES=4
PROCS=4
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/dune-multiscale/${DATADIR}_12C_n${PROCS}_${MA}x${MI}_${SUF} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI ${COMMON}"
srun -n $PROCS -N $NODES $BIN ${OPT} &

NODES=2
PROCS=2
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/dune-multiscale/${DATADIR}_12C_n${PROCS}_${MA}x${MI}_${SUF} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI ${COMMON}"
srun -n $PROCS -N $NODES $BIN ${OPT}  
wait
