#!/bin/bash -l 
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=1 
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=12
#SBATCH --mem=4gb 
#SBATCH --time=02:00:00 
#SBATCH --account=UniKoeln 
#SBATCH --partition=mpi
#SBATCH --constraint=[inca12*16]
#SBATCH --exclusive
#SBATCH -o out_%j_%N
#SBATCH -e out_%j_%N.err
#SBATCH --mail-user=rmilk@uni-koeln.de
#SBATCH --mail-type=end 

source $HOME/.modules
MA=16
MI=16
BIN=/scratch/rmilk/multiscale-build/dune-multiscale/elliptic_msfem
COMMON="-threading.partition_factor 1"
DATADIR=speedup
SUF="_T12"

NODES=16
PROCS=16
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops -global.datadir /scratch/rmilk/dune/single_run_np${NODES} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI ${COMMON}"
srun -n $PROCS -N $NODES $BIN ${OPT}

