#!/bin/bash -l 
#SBATCH --nodes={{ NODES }}
#SBATCH --ntasks-per-node=12
#SBATCH --ntasks={{ NODES * 12 }}
#SBATCH --cpus-per-task=1
#SBATCH --mem=23gb 
#SBATCH --time=02:00:00 
#SBATCH --account=UniKoeln 
#SBATCH --partition=mpi
#SBATCH --constraint=[inca12*{{ NODES }}]
#SBATCH --exclusive
#SBATCH -o out_pure_run_np_{{ NODES }}_out_{{ NODES }}_{{ MACRO }}x{{ MICRO }}_T{{ THREADS }}
#SBATCH -e out_pure_run_np_{{ NODES }}_out_{{ NODES }}_{{ MACRO }}x{{ MICRO }}_T{{ THREADS }}.err
#SBATCH --mail-user=rmilk@uni-koeln.de
#SBATCH --mail-type=end 

source $HOME/.modules

BIN=/scratch/rmilk/multiscale-build/dune-multiscale/elliptic_msfem
OPT="/home/rmilk/cmake_multiscale/dune-multiscale/parameter_files/cheops.ini \
    -global.datadir /scratch/rmilk/dune/pure_run_np_{{ NODES }}_out_{{ NODES }}_{{ MACRO }}x{{ MICRO }}_T{{ THREADS }} \
    -grids.macro_cells_per_dim {{ MACRO }} -grids.micro_cells_per_macrocell_dim {{ MICRO }} \
    -threading.max_count 1 "
srun -n {{ NODES * 12 }} -N {{ NODES }} $BIN ${OPT}

