#!/bin/bash
##
## optional: energy policy tags
#@ energy_policy_tag = et_32x16_512N_12C
# DO NOT USE environment = COPY_ALL
#@ job_type = MPICH
#@ class = general
#@ node = 128
#@ island_count=1
# other example
#@ tasks_per_node = 1
#@ wall_clock_limit = 0:10:30
##                    1 h 20 min 30 secs
#@ job_name = muc_test
#@ network.MPI = sn_all,not_shared,us
#@ initialdir = $(home)/multiscale-build/dune-multiscale
#@ output = job$(jobid).out
#@ error = job$(jobid).err
#@ notification=always
#@ notify_user=rene.milk@wwu.de
#@ queue
. /etc/profile
. /etc/profile.d/modules.sh
#setup of environment
source $HOME/.modules
#optional: 
#module load mpi_pinning/hybrid_blocked

MA=64
MI=16
THREADS=16
BIN=$HOME/multiscale-build/dune-multiscale/elliptic_msfem

NODES=512
PROCS=512
OPT="$HOME/dune-multiscale-super/dune-multiscale/parameter_files/supermuc_test -global.datadir $HOME/multiscale-build/dune-multiscale/speedup_n${PROCS}_${MA}x${MI}_T${THREADS} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI -threading.max_count ${THREADS} "
#mpiexec -n ${PROCS} $BIN ${OPT} 

NODES=256
PROCS=256
OPT="$HOME/dune-multiscale-super/dune-multiscale/parameter_files/supermuc_test -global.datadir $HOME/multiscale-build/dune-multiscale/speedup_n${PROCS}_${MA}x${MI}_T${THREADS} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI -threading.max_count ${THREADS} "
#mpiexec -n ${PROCS} $BIN ${OPT} 

NODES=128
PROCS=128
OPT="$HOME/dune-multiscale-super/dune-multiscale/parameter_files/supermuc_test -global.datadir $HOME/multiscale-build/dune-multiscale/speedup_n${PROCS}_${MA}x${MI}_T${THREADS} -grids.macro_cells_per_dim $MA -grids.micro_cells_per_macrocell_dim $MI -threading.max_count ${THREADS} "
mpiexec -n ${PROCS} $BIN ${OPT} 
