#!/usr/bin/python

import jinja2
import sys

algos = ['hmm', 'msfem', 'lodm']

tpl = jinja2.Template(u'''
# ** THIS FILE IS AUTOGENERATED, CHANGE MAKEFILE.AM.PY INSTEAD **
include $(top_srcdir)/common.mk

# tests where program to build and program to run are equal
NORMALTESTS = {% for algo in algos %}compare_{{algo}} {% endfor %}

# list of tests to run
TESTS = $(NORMALTESTS)

# programs just to build when "make check" is used
check_PROGRAMS = $(NORMALTESTS)


LDFLAGS = -lboost_timer -lboost_chrono -lboost_filesystem -lboost_system $(BOOST_LDFLAGS)
CXXFLAGS = $(BOOST_CPPFLAGS) $(DUNE_CPPFLAGS) \\
    -DGRIDDIM=$(GRIDDIM) -D$(GRIDTYPE) $(ALL_PKG_CPPFLAGS)

{% for algo in algos %}
compare_{{algo}}_SOURCES = compare_{{  algo|lower }}.cc
{% endfor %} 

EXTRA_DIST = $(SOURCES) {% for algo in algos %}compare_{{  algo|lower }}.dgf {% endfor %}

CLEANFILES = *.gcda *.gcno semantic.cache  dgfparser.log 

include $(top_srcdir)/am/global-rules
# ** THIS FILE IS AUTOGENERATED, CHANGE MAKEFILE.AM.PY INSTEAD **
''')
fn = sys.argv[0].replace('.py','')
with open(fn, 'wb') as out:
    out.write(tpl.render(algos=algos))
        
